export const jobs = [
  {
    id: '1',
    title: 'Assam Police Sub Inspector Recruitment',
    organization: 'Assam Police',
    vacancies: 450,
    salary: '₹14,000 - ₹60,500 + GP ₹8,700',
    qualification: 'Graduation',
    lastDate: '2026-07-10',
    category: 'Assam Govt',
    isNew: true,
    isHot: true,
  },
  {
    id: '2',
    title: 'SBI Probationary Officer (PO) 2026',
    organization: 'State Bank of India',
    vacancies: 2000,
    salary: '₹41,960 - ₹63,840',
    qualification: 'Graduation',
    lastDate: '2026-07-11',
    category: 'Central Govt',
    isNew: true,
    isHot: false,
  },
  {
    id: '3',
    title: 'Assam Direct Recruitment 2026 (Grade III & IV)',
    organization: 'Govt of Assam',
    vacancies: 12500,
    salary: '₹12,000 - ₹52,000',
    qualification: '8th / 10th / 12th / Degree',
    lastDate: '2026-07-15',
    category: 'Assam Govt',
    isNew: true,
    isHot: true,
  },
  {
    id: '4',
    title: 'SSC CGL Examination 2026',
    organization: 'Staff Selection Commission',
    vacancies: 7500,
    salary: 'Level 4 to Level 8',
    qualification: 'Bachelor Degree',
    lastDate: '2026-07-17',
    category: 'Central Govt',
    isNew: false,
    isHot: false,
  },
  {
    id: '5',
    title: 'HDFC Bank Customer Executive',
    organization: 'HDFC Bank',
    vacancies: 150,
    salary: '₹2.5 - ₹4.5 LPA',
    qualification: 'Any Graduate',
    lastDate: '2026-07-25',
    category: 'Private',
    isNew: true,
    isHot: false,
  },
];

export const updates = [
  { id: '1', title: 'ADRE Grade III Result Declared 2026', type: 'Result', date: '2026-07-09' },
  { id: '2', title: 'Assam Police Constable Admit Card Available', type: 'Admit Card', date: '2026-07-08' },
  { id: '3', title: 'Gauhati University PG Admission 2026 Started', type: 'Admission', date: '2026-07-07' },
  { id: '4', title: 'Directorate of Health Services Grade IV Result', type: 'Result', date: '2026-07-06' },
];

export const trending = [
  { id: '1', title: 'Assam Direct Recruitment 2026 Apply Online', views: '250K+' },
  { id: '2', title: 'Assam Police Constable 5563 Posts', views: '180K+' },
  { id: '3', title: 'SSC GD Constable 2026 Notification', views: '150K+' },
  { id: '4', title: 'Assam TET Cum Recruitment 2026', views: '120K+' },
  { id: '5', title: 'Railway RRB NTPC Recruitment', views: '95K+' },
];
